[book]
authors = ["Marius Weidner"]
language = "en"
text-direction = "ltr"
multilingual = false
src = "src"
title = "Programming Languages Group"
description = "Programming Languages Group – University of Freiburg"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "light"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
no-section-label = true
site-url = "/"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 1
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
