#!/usr/bin/env bash

# usage:  ./watch

# pull rebase auto stash
git pull --rebase --autostash

# select binary
platform="$(uname)"

if [ $platform == "Darwin" ]; then
    bin="mdbook-apple"      
elif [ "$(expr substr $platform 1 5)" == "Linux" ]; then
    bin="mdbook-linux"   
else
    echo "unsupported platform '$platform'".
    exit 1
fi

# run in watch mode
bin/$bin serve --dest-dir docs --open